### ISSUE TITLE
No cross reference links in generated pdf file

### ISSUE THREAD

**Issue by funnygerman** [mraible/infoq-mini-book#17]
There are no cross reference links for included chapters in the generated pdf document. It's just text.

Also all items in TOC are not clickable.

Just to make it clear, cross reference links are working fine in the epub, however I'm not sure if it's an issue of the asciidoctor.

**Comment by funnygerman** [comment]
> however I'm not sure if it's an issue of the asciidoctor.

Just checked if cross references links are working by using asciidoctor-pdf to generate pdf documents. And it works fine

**Comment by amejiarosario** [comment]
@funnygerman I have the same issue. Did you find a workaround?

**Comment by mraible** [comment]
I tried upgrading to the latest version of asciidoctor-pdf in `Gemfile`:

```
gem 'asciidoctor-pdf', github: 'asciidoctor/asciidoctor-pdf', ref: 'd7af149e0453b2327c4ec82505649bc76a0c16bf'
```

Unfortunately, this doesn't solve the problem. I'm not sure that the TOC every had clickable page numbers, but I agree it should. 

@mojavelinux - is this something that should work in Asciidoctor-PDF?

**Comment by mojavelinux** [comment]
@mraible I just noticed that a recent change to Asciidoctor caused a regression in cross references Asciidoctor PDF. I just pushed a fixed to master. Can you try again?

**Comment by mraible** [comment]
@mojavelinux I tried [updating to the latest version of asciidoctor-pdf](https://github.com/mraible/infoq-mini-book/pull/19), but it doesn't seem to help. The page numbers in the TOC are still not clickable.

**Comment by mojavelinux** [comment]
Oh, I see now. It's the optimize PDF script. For some reason, it's killing the internal links. I don't remember it doing that before, and I have no idea how to tel it not to do that. You could probably just get rid of this step. Another option is to use [hexapdf](https://hexapdf.gettalong.org/) to optimize, which is going to do a better job anyway.

```
bundle exec hexapdf optimize --force $OUT_DIR/index.pdf $OUT_DIR/index.pdf
```

50K using hexapdf vs 67K using gs.

So I strongly recommend to stop using optimize-pdf and use hexapdf instead. I'd be happy to send a PR to get you started.

**Comment by mraible** [comment]
@mojavelinux A PR would be great!

**Comment by mojavelinux** [comment]
PR sent!

**Comment by mojavelinux** [comment]
I looked into why ghostscript is removing links and I absolutely cannot figure out why or how to make it stop. What I can tell you is that it makes ghostscript practically useless. Thank goodness we have hexapdf to fall back on.

**Comment by mojavelinux** [comment]
Aha! SO FTW!

```
-dPrinted=false
```

I'll go ahead and add that upstream anyway. But I still recommend hexapdf as the default solution in this project.
